# Generated by Django 3.1.4 on 2020-12-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car',
            field=models.ImageField(default='', upload_to='cars/'),
        ),
    ]
